%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-eml
Version:        1.8.15
Release:        7%{?dist}%{?release_suffix}
Summary:        ROS eml package

License:        Binary Only
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-catkin
BuildRequires:  cmake
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This is an implementation of the EtherCAT master protocol for the PR2 robot
based on the work done at Flanders' Mechatronics Technology Centre.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/noetic

%changelog
* Tue Mar 02 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-7
- Autogenerated by Bloom

* Tue Mar 02 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-6
- Autogenerated by Bloom

* Tue Mar 02 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-5
- Autogenerated by Bloom

* Tue Mar 02 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-4
- Autogenerated by Bloom

* Mon Feb 22 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-3
- Autogenerated by Bloom

* Mon Feb 22 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-2
- Autogenerated by Bloom

* Mon Feb 22 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.8.15-1
- Autogenerated by Bloom

